#:schema node_modules/wrangler/config-schema.json
name = "cf-ai-workers"
main = "src/index.js"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

########### LOCAL ENVIRONMENT


kv_namespaces = [
	{ binding = "CHAT_SESSION", id = "9c2170a1650044d4a6ccc6be99cdd8cd", preview_id = "1f617718eecf43ebb61a1592c193fb50" },
	{ binding = "B2C_AGENT", id = "19f24243f5ae4b57b24bbffdbd2ce90e", preview_id = "82c51f22f0034da2bcfbb7b4472bdabe" },
	{binding = 'BENCHMARK', id = "c1be80bf1ef049b780bfe2e91db4a140", preview_id = "c1be80bf1ef049b780bfe2e91db4a140"}
]

[vars]
M2M_SECRET_KEY = "2esMBSsC9cnUJp8CghFGegzCPWem9a38h6XGXDRkDpwHPrRrm4kW3Aj9NCwxdcHE"
MP_SECRET_KEY="jstleeeWAusnTRXUktCaGxVVOZKpUHdqsbBsosqkQRPvakxFDa"
CF_ACCOUNT_ID = "30480d77542bf93db9202f8bf839a48c"
AUTH0_ISSUER = "https://vivasaml.uk.auth0.com/"
AUTH0_AUDIENCE = "https://api-testing.vivacityapp.com/"
AUTH0_CUSTOM_CLAIM_KEY = "http://vivacityapp.com/"
EMBEDDINGS_MODEL_NAME = "@cf/baai/bge-base-en-v1.5"
modelName = "@cf/qwen/qwen1.5-14b-chat-awq"
AZURE_OPENAI_API_KEY = "45da302bc5f544bbbf2d6f333ac28eb4"
AZURE_OPENAI_API_DEPLOYMENT_NAME = "gpt-4ooo"
AZURE_OPENAI_API_VERSION = "2023-05-15"
AZURE_OPENAI_API_INSTANCE_NAME = "viva-ai-dev"
TAVILY_API_KEY = "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"
B2C_AZURE_OPENAI_API_KEY = "45da302bc5f544bbbf2d6f333ac28eb4"
B2C_AZURE_OPENAI_API_VERSION = "2023-03-15-preview"
B2C_AZURE_OPENAI_API_INSTANCE_NAME = "viva-ai-dev"
B2C_EMBEDDINGS_API_KEY="45da302bc5f544bbbf2d6f333ac28eb4"
B2C_EMBEDDINGS_INSTANCE_NAME="viva-ai-dev"
B2C_EMBEDDINGS_DEPLOYMENT_NAME="text-embedding-3-large"
B2C_EMBEDDINGS_VERSION="2023-05-15"
B2C_LLM_TEMP = 0.2
SESSION_EXPIRATION=3600
DEBUG=1


[ai]
binding = "AI"

[[vectorize]]
binding = "B2C_AI_INDEX"
index_name = "b2c-ai-store"

[[vectorize]]
binding = "B2B_AI_INDEX" # available within worker on env.VECTORIZE_INDEX
index_name = "b2b-store-new"

[[vectorize]]
binding = "VECTORIZE_INDEX" # available within worker on env.VECTORIZE_INDEX
index_name = "glossaries-staging"

#
[[d1_databases]]
binding = "DB"
database_name = "translation-glossary"
database_id = "6496b036-704b-4d9b-a609-6361e03712c0"

[[d1_databases]]
binding = "VIVADB"
database_name = "vivacity_content"
database_id = "76718ef3-24f9-4f3b-a006-33b48c37c99d"


[[d1_databases]]
binding = "AIDB"
database_name = "ai-db"
database_id = "52527ea1-a1bc-4f44-afda-956d7aa8eea8"

[[migrations]]
tag = 'New class ChatHistory'
new_classes = ['ChatHistory']

[[migrations]]
tag = 'New class AI Agent'
new_classes = ['AIAgent']


########### DEVELOPMENT ENVIRONMENT

[env.development]

kv_namespaces = [
	{ binding = "CHAT_SESSION", id = "9c2170a1650044d4a6ccc6be99cdd8cd" },
	{ binding = "B2C_AGENT", id = "19f24243f5ae4b57b24bbffdbd2ce90e" },
	{binding = 'BENCHMARK', id = "c1be80bf1ef049b780bfe2e91db4a140"}
]

routes = [
	{ pattern = "api-testing.miyou.co/cf-ai/*", zone_id = "88b6f53c4ce2258bc9d859c88958748c" },
]

[env.development.vars]
M2M_SECRET_KEY = "2esMBSsC9cnUJp8CghFGegzCPWem9a38h6XGXDRkDpwHPrRrm4kW3Aj9NCwxdcHE"
MP_SECRET_KEY="jstleeeWAusnTRXUktCaGxVVOZKpUHdqsbBsosqkQRPvakxFDa"
CF_ACCOUNT_ID = "30480d77542bf93db9202f8bf839a48c"
AUTH0_ISSUER = "https://vivasaml.uk.auth0.com/"
AUTH0_AUDIENCE = "https://api-testing.vivacityapp.com/"
AUTH0_CUSTOM_CLAIM_KEY = "http://vivacityapp.com/"
EMBEDDINGS_MODEL_NAME = "@cf/baai/bge-base-en-v1.5"
AZURE_OPENAI_API_KEY = "45da302bc5f544bbbf2d6f333ac28eb4"
AZURE_OPENAI_API_DEPLOYMENT_NAME = "gpt-4ooo"
AZURE_OPENAI_API_VERSION = "2023-05-15"
AZURE_OPENAI_API_INSTANCE_NAME = "viva-ai-dev"
TAVILY_API_KEY = "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"
B2C_AZURE_OPENAI_API_KEY = "45da302bc5f544bbbf2d6f333ac28eb4"
B2C_AZURE_OPENAI_API_VERSION = "2023-03-15-preview"
B2C_AZURE_OPENAI_API_INSTANCE_NAME = "viva-ai-dev"
B2C_EMBEDDINGS_API_KEY="45da302bc5f544bbbf2d6f333ac28eb4"
B2C_EMBEDDINGS_INSTANCE_NAME="viva-ai-dev"
B2C_EMBEDDINGS_DEPLOYMENT_NAME="text-embedding-3-large"
B2C_EMBEDDINGS_VERSION="2023-05-15"
B2C_LLM_TEMP = 0.2
SESSION_EXPIRATION=3600
DEBUG=1


[env.development.ai]
binding = "AI"

[[env.development.vectorize]]
binding = "VECTORIZE_INDEX" # available within worker on env.VECTORIZE_INDEX
index_name = "glossaries"

[[env.development.vectorize]]
binding = "B2B_AI_INDEX"
index_name = "b2b-store-new"

[[env.development.vectorize]]
binding = "B2C_AI_INDEX"
index_name = "b2c-ai-store"

[[env.development.d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "translation-glossary"
database_id = "6496b036-704b-4d9b-a609-6361e03712c0"

[[env.development.d1_databases]]
binding = "VIVADB"
database_name = "vivacity_content"
database_id = "76718ef3-24f9-4f3b-a006-33b48c37c99d"

[[env.development.d1_databases]]
binding = "AIDB"
database_name = "ai-db"
database_id = "52527ea1-a1bc-4f44-afda-956d7aa8eea8"

[[env.development.queues.producers]]
queue = "data-storage-dev"
binding = "MY_QUEUE"

[[env.development.queues.consumers]]
queue = "data-storage-dev"
max_batch_size = 100
max_batch_timeout = 30


########### STAGING ENVIRONMENT

[env.staging]

kv_namespaces = [
	{ binding = "CHAT_SESSION", id = "05a5a58563a047ccbce86d301aebef1f" },
	{ binding = "B2C_AGENT", id = "a26b585729284638ac7350c5ab831125" }
]
routes = [
	{ pattern = "api-staging.vivacityapp.com/cf-ai/*", zone_id = "d343da912d009c8bccbd2352c85dad9a" },
]

[env.staging.vars]
M2M_SECRET_KEY = "H42e7MVmzSGUZeByUA2XjnHvhjbs2jPBvuMDZwZ3gMw3h6wfuVkQhbY88hmqvZqe"
MP_SECRET_KEY="rmfMgSdEoXUIexoByhNRNNLiIWmkqCuBQhBWOKBqihvfXsPPEw"
CF_ACCOUNT_ID = "5ff5e53470602f594510405e2e07a620"
AUTH0_ISSUER = "https://viva-staging.uk.auth0.com/"
AUTH0_AUDIENCE = "https://api-staging.vivacityapp.com/"
AUTH0_CUSTOM_CLAIM_KEY = "http://vivacityapp.com/"
EMBEDDINGS_MODEL_NAME = "@cf/baai/bge-base-en-v1.5"
AZURE_OPENAI_API_KEY = "45da302bc5f544bbbf2d6f333ac28eb4"
AZURE_OPENAI_API_DEPLOYMENT_NAME = "gpt-4ooo"
AZURE_OPENAI_API_VERSION = "2023-05-15"
AZURE_OPENAI_API_INSTANCE_NAME = "viva-ai-dev"
TAVILY_API_KEY = "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"
B2C_AZURE_OPENAI_API_KEY = "45da302bc5f544bbbf2d6f333ac28eb4"
B2C_AZURE_OPENAI_API_VERSION = "2023-03-15-preview"
B2C_AZURE_OPENAI_API_INSTANCE_NAME = "viva-ai-dev"
B2C_EMBEDDINGS_API_KEY="45da302bc5f544bbbf2d6f333ac28eb4"
B2C_EMBEDDINGS_INSTANCE_NAME="viva-ai-dev"
B2C_EMBEDDINGS_DEPLOYMENT_NAME="text-embedding-3-large"
B2C_EMBEDDINGS_VERSION="2023-05-15"
B2C_LLM_TEMP = 0.2
SESSION_EXPIRATION=3600

[env.staging.ai]
binding = "AI"

[[env.staging.vectorize]]
binding = "VECTORIZE_INDEX" # available within worker on env.VECTORIZE_INDEX
index_name = "glossaries-staging"

[[env.staging.vectorize]]
binding = "B2B_AI_INDEX" # available within worker on env.VECTORIZE_INDEX
index_name = "b2b-store-staging"

[[env.staging.vectorize]]
binding = "B2C_AI_INDEX"
index_name = "b2c-ai-store-staging"


[[env.staging.d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "translation-glossary-staging"
database_id = "a3ed53d7-7c2a-417b-b62b-a0b79c08a6c7"

[[env.staging.d1_databases]]
binding = "VIVADB"
database_name = "vivacity_content_staging"
database_id = "686cda0c-d390-4658-a263-d77627d895a1"

[[env.staging.d1_databases]]
binding = "AIDB"
database_name = "ai-db"
database_id = "8eb75094-a63d-4a8d-aff8-2b15a1e8843f"

[[env.staging.queues.producers]]
queue = "data-storage-staging"
binding = "MY_QUEUE"

[[env.staging.queues.consumers]]
queue = "data-storage-staging"
max_batch_size = 100
max_batch_timeout = 30


########### PRODUCTION ENVIRONMENT

[env.production]

tail_consumers = [{service = "cf-ai-workers-production-tail"}]

kv_namespaces = [
	{ binding = "CHAT_SESSION", id = "bf1ad8141d30453fa7c677a8667a5fbb" },
	{ binding = "B2C_AGENT", id = "2cdf6bd0811e45219bf43633924b06ee" }
]

routes = [
	{ pattern = "api-prod.vivacityapp.com/cf-ai/*", zone_id = "d343da912d009c8bccbd2352c85dad9a" },
]

[env.production.vars]
M2M_SECRET_KEY = "H42e7MVmzSGUZeByUA2XjnHvhjbs2jPBvuMDZwZ3gMw3h6wfuVkQhbY88hmqvZqe"
MP_SECRET_KEY="czwsgUVbQfVCFSYHsZiGlpNZoAmzPAiyycsWyxWoazyDQxURtT"
CF_ACCOUNT_ID = "5ff5e53470602f594510405e2e07a620"
AUTH0_ISSUER = "https://auth.vivacityapp.com/"
AUTH0_AUDIENCE = "https://api-prod.vivacityapp.com"
AUTH0_CUSTOM_CLAIM_KEY = "http://vivacityapp.com/"
EMBEDDINGS_MODEL_NAME = "@cf/baai/bge-base-en-v1.5"
AZURE_OPENAI_API_KEY = "6f8044f0489940cb8f50d460bceb5dd0"
AZURE_OPENAI_API_DEPLOYMENT_NAME = "vivacity-gpt-4o"
AZURE_OPENAI_API_VERSION = "2023-05-15"
AZURE_OPENAI_API_INSTANCE_NAME = "viva-ai"
TAVILY_API_KEY = "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"
B2C_AZURE_OPENAI_API_KEY = "b1cb005e67bc4cea965a941872e20c82"
B2C_AZURE_OPENAI_API_VERSION = "2024-08-01-preview"
B2C_AZURE_OPENAI_API_INSTANCE_NAME = "vivacity-b2c-uk-south"
B2C_EMBEDDINGS_API_KEY="b1cb005e67bc4cea965a941872e20c82"
B2C_EMBEDDINGS_INSTANCE_NAME="vivacity-b2c-uk-south"
B2C_EMBEDDINGS_DEPLOYMENT_NAME="text-embedding-3-large"
B2C_EMBEDDINGS_VERSION="2023-05-15"
B2C_LLM_TEMP = 0.2
SESSION_EXPIRATION=3600
DEBUG = 1

[env.production.ai]
binding = "AI"

[[env.production.vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "glossaries"

[[env.production.vectorize]]
binding = "B2B_AI_INDEX" # available within worker on env.VECTORIZE_INDEX
index_name = "b2b-store-new"

[[env.production.vectorize]]
binding = "B2C_AI_INDEX"
index_name = "b2c-ai-store"


[[env.production.d1_databases]]
binding = "DB"
database_name = "translation-glossary"
database_id = "c6b3b08e-2e15-4fd5-bb47-5cbad5827c86"

[[env.production.d1_databases]]
binding = "VIVADB"
database_name = "vivacity_content"
database_id = "c7613b50-7849-4cde-82fd-10fe16f29eef"

[[env.production.d1_databases]]
binding = "AIDB"
database_name = "ai-db"
database_id = "efc9b416-e9ce-40d2-aeb1-75f054d94b11"

[[env.production.queues.producers]]
queue = "data-storage"
binding = "MY_QUEUE"

[[env.production.queues.consumers]]
queue = "data-storage"
max_batch_size = 100
max_batch_timeout = 30
